# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-24 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadDate', models.DateTimeField(auto_created=True)),
                ('filename', models.CharField(max_length=200)),
                ('filedesc', models.CharField(default='', max_length=100)),
                ('filedir', models.ImageField(default='pics/download.jpeg', upload_to='pics/')),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foldername', models.CharField(max_length=200)),
                ('folderdesc', models.CharField(max_length=300)),
                ('parent_folder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drive.Folder')),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='parent_folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drive.Folder'),
        ),
    ]
